version: "3.9"

services:
  app:
    build: .
    image: peplink-finder:latest
    restart: unless-stopped
    environment:
      - PEPLINK_DATA_PATH=/app/data/hardware_data.json
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - GUNICORN_TIMEOUT=60
    expose:
      - "8000"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-finder.peplink.com}
      - EMAIL=${EMAIL:-admin@peplink.com}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data: {}
  caddy_config: {}
